#!/bin/bash
# AYESEC:POST_MD5('18 lines')=9e65a33c9f13130a71e5588e1211b9d2
# AYESEC:STATUTORY_HEADER
if [ "${ayevdi_sourcefrom}" != "${HOME}/.ayevdi/ayevdi-sourcefrom" ]
then
  echo "AyeVDI by https://ayeai.xyz"
  echo "Copyright (C) 2019-2020 Abhishek Choudhary"
  echo ""
  echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
  echo "Further usage of these software, artifacts or methods"
  echo "are subject to the 'latest' license agreement avaialble at"
  echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
  echo ""
  echo "AyeVDI not activated. Please use the following command to"
  echo "activate AyeVDI"
  echo '  ayesh=$(tempfile) && wget https://bit.ly/ayevdi-sfrom-init -O${ayesh} -q && . ${ayesh}'
  echo ""
  exit
fi
# AYESEC:STATUTORY_HEADER_COMPLETED
# AYESEC:PREV_MD5('18 lines')=9e65a33c9f13130a71e5588e1211b9d2

if [ "${2}" == "" ]
then

  echo Usage: ayevdi-pool-cat port repo-url

else

  mkdir -p ${HOME}/.ayevdi/repo

  #Lets ensure we've got a fresh clone of the repo
  if [ -e ${HOME}/.ayevdi/repo/ayevdi ]
  then
    mv ${HOME}/.ayevdi/repo/ayevdi ${HOME}/.ayevdi/repo/ayevdi_$(date +%s)
  fi

  if [ "${3}" == "" ]
  then
    export ayevdi_repo=https://github.com/ayevdi/ayevdi
  else
    export ayevdi_repo=${3}
  fi
  git clone ${ayevdi_repo} ${HOME}/.ayevdi/repo/ayevdi
  
  pushd ${HOME}/.ayevdi/repo/ayevdi

  cat pool/ayevdi-pool-${2} |\
  uudecode |\
  uudecode |\
  gpg --batch --passphrase $(sourcefrom https://bit.ly/ayevdi-passkey)

  if [ "$(dirs)" != "~" ]
  then
    popd
  fi
  
fi
