#!/bin/bash
# AYESEC:POST_MD5('18 lines')=9e65a33c9f13130a71e5588e1211b9d2
# AYESEC:STATUTORY_HEADER
if [ "${ayevdi_sourcefrom}" != "${HOME}/.ayevdi/ayevdi-sourcefrom" ]
then
  echo "AyeVDI by https://ayeai.xyz"
  echo "Copyright (C) 2019-2020 Abhishek Choudhary"
  echo ""
  echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
  echo "Further usage of these software, artifacts or methods"
  echo "are subject to the 'latest' license agreement avaialble at"
  echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
  echo ""
  echo "AyeVDI not activated. Please use the following command to"
  echo "activate AyeVDI"
  echo '  ayesh=$(tempfile) && wget https://bit.ly/ayevdi-sfrom-init -O${ayesh} -q && . ${ayesh}'
  echo ""
  exit
fi
# AYESEC:STATUTORY_HEADER_COMPLETED
# AYESEC:PREV_MD5('18 lines')=9e65a33c9f13130a71e5588e1211b9d2

# TBD: Check dependencies on sudoer's privilige
# sudo usermod -aG sudo ${uuid}
# newgrp sudo

# These commands should not be run at every instance - only the first time
if [ ! -e ${HOME}/.ayevdi/ayevdi-host-user-setup.done ]
then
  # TBD: Create abstraction to call other containerization infra
  # like Singularity or AyeCons
  
  # Install docker.io and enable docker service
  logger "Installing docker.io"
  sudo apt update -y
  sudo apt install -y docker.io
  sudo systemctl enable docker &&\
  logger "SUCESS:INSTALL:docker.io"
  # TBD: Abstract installation and validation

  # Enable user to execute docker commands
  logger "Enabling docker privileges"
  sudo groupadd docker
  sudo usermod -aG docker ${USER}
  mkdir -p /home/"${USER}"/.docker
  sudo chown "${USER}":"${USER}" /home/"$USER"/.docker -R
  sudo chmod g+rwx "/home/"${USER}"/.docker" -R
  newgrp docker
  docker ps &&\
  date +%s >${HOME}/.ayevdi/ayevdi-host-user-setup.done &&\
  logger "SUCCESS:CONFIG:docker privileges"
fi
