#!/bin/bash
# AYESEC:POST_MD5('64 lines')=7cb48d17aa719f54344a715a9b2a34ae
# AYESEC:FILE_TOP('ayevdi/doc/ayevdi-mascot')

# AYESEC:POST_MD5('18 lines')=9e65a33c9f13130a71e5588e1211b9d2
# AYESEC:STATUTORY_HEADER
if [ "${ayevdi_sourcefrom}" != "${HOME}/.ayevdi/ayevdi-sourcefrom" ]
then
  echo "AyeVDI by https://ayeai.xyz"
  echo "Copyright (C) 2019-2020 Abhishek Choudhary"
  echo ""
  echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
  echo "Further usage of these software, artifacts or methods"
  echo "are subject to the 'latest' license agreement avaialble at"
  echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
  echo ""
  echo "AyeVDI not activated. Please use the following command to"
  echo "activate AyeVDI"
  echo '  ayesh=$(tempfile) && wget https://raw.githubusercontent.com/ayevdi/ayevdi/master/ost/ayevdi-sfrom-init -O${ayesh} -q && . ${ayesh}'
  echo ""
  exit
fi
# AYESEC:STATUTORY_HEADER_COMPLETED
# AYESEC:PREV_MD5('18 lines')=9e65a33c9f13130a71e5588e1211b9d2

# AYESEC:POST_MD5('37 lines')=5d3998cb9f2c1c13482a2a85d665f4d2
# AYESEC:REPRESENTATION_NOTICE_START

# AYESEC:POST_MD5('11 lines')=bd07ab427e2502496d03ebbf9fb503d5
# AYESEC:DRIKSH_START
#                  AyeVDI   ##@###&
#              /^^^^^^^"""####  o ##:
#             /      Driksh      ##''
#             (  The Immutable  ##{,,
#             { \   /++++++++/  #### 
#               /  /  \     /  /  \  
#              /__/ \__\   /__/ \__\ 
# (C) Copyright 2020 Abhishek Choudhary. All rights reserved.
#          MADE IN INDIA | BHARAT MEIN NIRMIT
# AYESEC:DRIKSH_COMPLETE
# AYESEC:PREV_MD5('11 lines')=bd07ab427e2502496d03ebbf9fb503d5

# NOTICE: This above lines 30-40 are NOT TO BE USED IN DERIVATIVES.
# The above artwork, the business marks AyeVDI, Driksh, and 
# the tagline 'Driksh - The Immutable' are intellectual property
# of Abhishek Choudhary (the original author) and may not be
# reproduced without permission. All rights including media
# and cinematic rights reserved. Derivatives must replace the
# artwork, logo, representation, trademarks appropriately,
# without violating the terms and conditions of the license
# agreement. Unmodified distributions must carry the above lines
# as is. Subject to the jurisdiction on courts in
# Hyderabad, Telangana, India only.
#
# Driksh in Sanskrit is close in meaning to manifestation

# The following command is the only valid method of displaying
# the AyeVDI and Driksh - The Immutable business marks with the
# lion graphic device. It must be executed on inside a bash shell
# on a color capable terminal with lolcat version 42.0.99 installed.
wget https://raw.githubusercontent.com/ayevdi/ayevdi/master/doc/ayevdi-mascot -O- -q | head -39 | tail -9 | cut -c 3- | lolcat -F 0.7 -S 2020 -p 20

# AYESEC:REPRESENTATION_NOTICE_COMPLETE
# AYESEC:PREV_MD5('37 lines')=5d3998cb9f2c1c13482a2a85d665f4d2

# AYESEC:FILE_END('ayevdi/doc/ayevdi-mascot')
# AYESEC:PREV_MD5('64 lines')=7cb48d17aa719f54344a715a9b2a34ae
