#!/bin/bash
# AYESEC:POST_MD5('18 lines')=9e65a33c9f13130a71e5588e1211b9d2
# AYESEC:STATUTORY_HEADER
if [ "${ayevdi_sourcefrom}" != "${HOME}/.ayevdi/ayevdi-sourcefrom" ]
then
  echo "AyeVDI by https://ayeai.xyz"
  echo "Copyright (C) 2019-2020 Abhishek Choudhary"
  echo ""
  echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
  echo "Further usage of these software, artifacts or methods"
  echo "are subject to the 'latest' license agreement avaialble at"
  echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
  echo ""
  echo "AyeVDI not activated. Please use the following command to"
  echo "activate AyeVDI"
  echo '  ayesh=$(tempfile) && wget https://raw.githubusercontent.com/ayevdi/ayevdi/master/ost/ayevdi-sfrom-init -O${ayesh} -q && . ${ayesh}'
  echo ""
  exit
fi
# AYESEC:STATUTORY_HEADER_COMPLETED
# AYESEC:PREV_MD5('18 lines')=9e65a33c9f13130a71e5588e1211b9d2

export tmpres=$(tempfile)
( for tl in 121 61 5
do 
  export timelimit=${tl}
  docker stop $(docker ps -aq)
  docker rm $(docker ps -aq)
  for i in {1..5}
  do 
    docker run --name ayetest_${i} -dt ayeai/ayevdi:$(sourcefrom https://raw.githubusercontent.com/ayevdi/ayevdi/master/image/ayevdi-image-common)
  done
  sourcefrom https://raw.githubusercontent.com/ayevdi/ayevdi/master/node/ayevdi-node-policy-timeout
done ) >${tmpres}

export stp=$(cat ${tmpres} | grep 'stop attempt' | wc -l)
export w1=$(cat ${tmpres} | grep '1 min' | wc -l)
export w2=$(cat ${tmpres} | grep '2 mins' | wc -l)
if [ ${stp} -eq 5 ] && [ ${w1} -eq 5 ] && [ ${w2} -eq 5 ]
then
  echo SUCCESS
else
  echo FAIL
fi
