#!/bin/bash
# AYESEC:POST_MD5('22 lines')=401df8541f58e70fd7f1fd004268c689
# AyeVDI
# Virtualized Deployment IaaS (VDI) by AyeAI
# 
# NOTICE
# Copyright (C) 2019-2020 Abhishek Choudhary
# 
# To all WHO IT MAY CONCERN,
# Greetings,
# All artifacts and methods in this project are offered with 
# NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only),
# subject to the jurisdictions of courts in Hyderabad, India,
# and solely in accordance with AyeAI SPL version 1, or later,
# as expressed at the follow URL and at the most current update
# https://raw.githubusercontent.com/ayeai/spl/master/LICENSE
# incuding its clauses of automatic implicit update of license,
# and unless in conflict the terms and conditions of GNU GPL v2
# shall apply with no retort to other GPL licenses, AND, These
# terms and conditions are implied read, understood and accepted
# by the access, or usage of these artifacts and methods which
# must STRICTLY be IN ACCORDANCE, and this notice must be 
# reproduced in derivatives along with the original assertions
# of copyrights and other rights reserved.
# AYESEC:PREV_MD5('22 lines')=401df8541f58e70fd7f1fd004268c689

# AYESEC:POST_MD5('39 lines')=62a59848c30b5e38013ee5b75693bf2d
# AYESEC:ONE_FILE_EXCEPTION("ayevdi-sfrom-init")
# This is an exception header for ayevdi-sfrom-init as AyeVDI
# is not expected to have been initialized till this file is
# called. Hereafter, use the follwing sample in each script
# header. For other types of artifacts, please see URL below
# http://bit.ly/ayevdi-header-samples
# Sample bash statutory header:
#   To use see output of the command below (without #)
#   wget http://bit.ly/ayevdi-sfrom-init -O- -q | cut -c 2- | head -55 | tail -18
## AYESEC:POST_MD5('18 lines')=9e65a33c9f13130a71e5588e1211b9d2
## AYESEC:STATUTORY_HEADER
#if [ "${ayevdi_sourcefrom}" != "${HOME}/.ayevdi/ayevdi-sourcefrom" ]
#then
#  echo "AyeVDI by https://ayeai.xyz"
#  echo "Copyright (C) 2019-2020 Abhishek Choudhary"
#  echo ""
#  echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
#  echo "Further usage of these software, artifacts or methods"
#  echo "are subject to the 'latest' license agreement avaialble at"
#  echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
#  echo ""
#  echo "AyeVDI not activated. Please use the following command to"
#  echo "activate AyeVDI"
#  echo '  ayesh=$(tempfile) && wget https://bit.ly/ayevdi-sfrom-init -O${ayesh} -q && . ${ayesh}'
#  echo ""
#  exit
#fi
## AYESEC:STATUTORY_HEADER_COMPLETED
## AYESEC:PREV_MD5('18 lines')=9e65a33c9f13130a71e5588e1211b9d2

if [ ! -f ${HOME}/.ayevdi/ayevdi-sourcefrom ]
then
  mkdir -p ${HOME}/.ayevdi/
  wget https://bit.ly/ayevdi-sfrom -O- -q > ${HOME}/.ayevdi/ayevdi-sourcefrom
fi

export ayevdi_sourcefrom=${HOME}/.ayevdi/ayevdi-sourcefrom

# AYESEC:ONE_FILE_EXCEPTION_COMPLETED
# AYESEC:PREV_MD5('39 lines')=62a59848c30b5e38013ee5b75693bf2d

# AYESEC:POST_MD5('18 lines')=9e65a33c9f13130a71e5588e1211b9d2
# AYESEC:STATUTORY_HEADER
if [ "${ayevdi_sourcefrom}" != "${HOME}/.ayevdi/ayevdi-sourcefrom" ]
then
  echo "AyeVDI by https://ayeai.xyz"
  echo "Copyright (C) 2019-2020 Abhishek Choudhary"
  echo ""
  echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
  echo "Further usage of these software, artifacts or methods"
  echo "are subject to the 'latest' license agreement avaialble at"
  echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
  echo ""
  echo "AyeVDI not activated. Please use the following command to"
  echo "activate AyeVDI"
  echo '  ayesh=$(tempfile) && wget https://bit.ly/ayevdi-sfrom-init -O${ayesh} -q && . ${ayesh}'
  echo ""
  exit
fi
# AYESEC:STATUTORY_HEADER_COMPLETED
## AYESEC:PREV_MD5('18 lines')=9e65a33c9f13130a71e5588e1211b9d2

# AYEINTERNS:TASK:Automate generation of file level and section MD5 sum
# Suggestions: Use tags to autofill the lines covered and the md5 sum
# AYEINTERNS:TASK_END

# AYEINTERNS:TASK:Automate validation of file level and section MD5 sum
# Suggestions: Ensure correctness and validity of the vaidator itself!
# AYEINTERNS:TASK_END

# AYESEC:POST_MD5('28 lines')=85f2c42b60793849126c554fb37de0a7
# AYESEC_NOTICE:'The following 27 lines must not be modified or removed'
# AYESEC:POST_MD5('25 lines')=1d63f7a217c7d7b1090f8460594bfcee
# AYESEC:SIGNATURE_PLAINTEXT_SOURCEFROM
# Line 2
echo "Welocome to AyeVDI by https://ayeai.xyz"
echo "Copyright (C) 2019-2020 Abhishek Choudhary"
echo ""
# Line 6
echo "AyeVDI sourcefrom activated!"
echo ""
echo "NO WARRANTY, and ZERO LIABILITY (Limited to INR 1/- only)"
echo "Further usage of these software, artifacts or methods"
echo "are subject to the 'latest' license agreement avaialble at"
echo "https://raw.githubusercontent.com/ayeai/spl/master/LICENSE"
echo ""
# Line 14
echo "If you do not accept the above terms and conditions, you"
echo "may not use this software, and are at liberty to use the"
echo "following commands in a bash terminal to remove traces,"
echo "under the supervision of someone familiar with 'bash shell'"
echo "         rm -rf ${HOME}/.ayevdi"
echo "         export ayevdi_sourcefrom=THANK YOU"
echo ""
echo "Towards greater glories with peace on Earth and beyond..."
echo ""
# Line 24
# AYESEC:SIGNATURE_PLAINTEXT_SOURCEFROM_COMPLETED
# AYESEC:PREV_MD5('25 lines')=1d63f7a217c7d7b1090f8460594bfcee
# AYESEC:PREV_MD5('28 lines')=85f2c42b60793849126c554fb37de0a7
